# Generated by Django 5.1.2 on 2024-11-28 08:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_review_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image5'),
            preserve_default=False,
        ),
    ]
