# Generated by Django 5.1.3 on 2024-11-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='main_characteristics',
        ),
    ]
