# Generated by Django 5.1.3 on 2024-12-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wholesaler_price',
        ),
    ]
