# Generated by Django 5.1.2 on 2025-02-01 17:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_product_image4_alter_product_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image5'),
        ),
    ]
