# Generated by Django 5.1.2 on 2025-02-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
