# Generated by Django 5.1.3 on 2025-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='by_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='by_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
