# Generated by Django 5.1.3 on 2025-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_payment_method_order_by_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='application',
            field=models.BooleanField(default=False),
        ),
    ]
