# Generated by Django 5.1.2 on 2025-02-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
