# Generated by Django 5.1.2 on 2025-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='application',
            field=models.BooleanField(default=False),
        ),
    ]
