# Generated by Django 5.1.2 on 2025-02-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_total_price_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
    ]
