# Generated by Django 5.1.2 on 2025-02-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
